src/egl/drivers/dri2/platform_android.c
Sometimes, when min_buffer_count is equal to max_buffer_count(1),
the buffer count will still be 1. And we will not conside 1 more
dequeue buffer. This will cause "setBufferCount" error in framework.
Tests: Fix CTS Media issues android.media.cts.HeifWriterTest
Signed-off-by: Chenglei Ren <chenglei.ren@intel.com>
Tracked-On: OAM-91605
=> Fix 4 CTS Media issues

src/util/macros.h, src/util/ralloc.c
This combines two upstream patches which could help fix
CtsGwpAsanTestCases crash on x86_64
391eeb744356353e96ce34f23b8b16b718a02d61
util: add a alignof() macro
Signed-off-by: Rhys Perry <pendingchaos02@gmail.com>
Reviewed-by: Eric Anholt <eric@anholt.net>
a4c708dd24e5ba8ac381973c14db8d23f4ac97bf
On some malloc implementation, malloc doesn't always align to 16
bytes even on 64 bits system. To make sure ralloc_header always
starts at the wanted alignment, just force the size to be aligned at
the alignment of ralloc_header. This fixes crashed on instruction
like "movaps %xmm0,0x10(%rax)" which requires aligned memory access.
Signed-off-by: Lepton Wu <lepton@chromium.org>
Reviewed-by: Marek Olšák <marek.olsak@amd.com>
Tracked-On: OAM-95765
=> UPSTREAM: Fix CtsGwpAsanTestCases crash on x86_64

Android.mk
This is required as part of enabling path
restrictions in Android 11
Tracked-On: OAM-95316
Signed-off-by: yaravapa <yasoda.aravapalli@intel.com>
=> Update PYTHONPATH to include Mako

src/gallium/drivers/iris/iris_bufmgr.c
=> one tmp fix for iris driver crash on x86 platform

src/mesa/main/framebuffer.c
IMPLEMENTATION_COLOR_READ_FORMAT is for optimization purpose.
if return GL_NONE, just indicated there was no optimized
additional format-type can be used. So we devide to remove
INVALID_OPERATION error generation.
Tracked-On: OAM-95725
Signed-off-by: Lu Yang <yang.a.lu@intel.com>
=> INTERNAL: Remove INVALID_OPERATION error generation

src/gallium/drivers/iris/iris_screen.c
With get_driver_query_group_info and get_driver_query_info
set, call to kernel to get performance information results
in CFI kernel panic.
As its not must to provide performance information, remove
setting of get_driver_query_group_info and get_driver_query_info.
Tracked-On: OAM-96773
Signed-off-by: Jeevaka Prabu Badrappan <jeevaka.badrappan@intel.com>
=> W/A: Remove performance info query resulting in CFI kernel panic

src/mesa/state_tracker/st_manager.c
This patch try to fix a deadlock issue when runing
android.media.cts.HeifWriterTest#testInputSurface_Grid_Handler
In this case, there are two deadlock threads involved, the HeifWriter
thread and a drawframe thread. The drawframe thread will try to draw a
frame and send it to HeifWriter. By calling st_api_make_currentst() it
will pending in surface dequeubuffer() with hold of EGL lock, and will
block HeifWriter thread executing, the buffer will be returned after
HeifWriter handled, In this case HeifWriter waiting for the EGL lock,
and drawframe thread wait for buffer with EGL lock hold, so deadlock
produced.
In case this is not the first time run of make_current(), allocate
buffer can be postponed, and allocate buffer in a context without
hold of EGL lock.
Signed-off-by: Yang, Dong …
=> INTERNEL: fix a deadlock during execute CTS cases

src/gallium/winsys/virgl/drm/virgl_drm_winsys.c
We should confirm height & width valid before call
create_resource, otherwise virglrenderer driver will
run into error.
Tracked-On: OAM-97927
Signed-off-by: Ren Chenglei <chenglei.ren@intel.com>
=> INTERNEL: Check height & width before create resource

Android.mk, src/compiler/Android.glsl.gen.mk, src/freedreno/Android.ir3.mk, src/mesa/program/Android.mk
This patch points the m4, flex and bison to the prebuilts
binary.
Signed-off-by: Tanuj Tekriwal <tanuj.tekriwal@intel.com>
=> [INTERNAL] Pointing flex and bison to prebuilts

src/egl/drivers/dri2/platform_android.c
This change is to correct plane number for
P010 format. The expected plane number should
be 2, but we got 3, which caused no image created
for P010 display.
Tracked-On: OAM-100284
Signed-off-by: Chen, Tianmi <tianmi.chen@intel.com>
=> Fix 10bit video display issue

src/gallium/drivers/iris/iris_screen.c
fd created needs protection to avoid being closed by other threads
fixed double close issue in iris_screen_destroy() function.
Tracked-On: OAM-102221
Signed-off-by: Basanagouda Koppad <basanagoudax.n.koppad@intel.com>
=> Add fd protection in mesa3d library

src/gallium/drivers/iris/iris_screen.c
Duplicate DRM file descriptor internally instead of reuse.
Tracked-On: OAM-102298
Signed-off-by: Basanagouda Koppad <basanagoudax.n.koppad@intel.com>
=> INTERNAL: Duplicate fd in iris driver instead of reuse

meson_options.txt
During building Android-13, the following error appears:
meson.build:21:0: ERROR: New value 33 is more than maximum value 31.
Tracked-On: OAM-103588
Signed-off-by: svenate <salini.venate@intel.com>
=> meson_options: Bump max value of platform-sdk-version to 33

subprojects/zlib.wrap
Remove zlib.wrap first.
Then using "meson wrap install zlib" to add it back
Signed-off-by: Yonggang Luo <luoyonggang@gmail.com>
Reviewed-by: Jesse Natalie <jenatali@microsoft.com>
Part-of: <https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/19187>
Tracked-On: OAM-104422
Signed-off-by: Lu Yang A <yang.a.lu@intel.com>
=> meson: upgrade zlib wrap to 1.2.13 for CVE issue

subprojects/zlib.wrap
Remove zlib.wrap first.
Then using "meson wrap install zlib" to add it back
Signed-off-by: Yonggang Luo <luoyonggang@gmail.com>
Reviewed-by: Jesse Natalie <jenatali@microsoft.com>
Part-of: <https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/19187>
Tracked-On: OAM-104421
Signed-off-by: Lu Yang A <yang.a.lu@intel.com>
=> meson: upgrade zlib wrap to 1.2.13

src/gallium/drivers/iris/iris_bufmgr.c
Currently the iris driver is adding the buffer objects to zombie list without checking if it is busy or not. It checks for it after 1 second which adds delay to buffer release.
This fix checks if the bo is busy or not before adding it to zombie list.
Without this fix, the applications expecting immediate buffer release would fail.
The fix is identified while debugging below cts tests: 
android.graphics.cts.BitmapTest#testDrawingHardwareBitmapNotLeaking android.graphics.cts.BitmapTest#testHardwareBitmapNotLeaking
Tracked-On: OAM-105862
Signed-off-by: Sai Teja Pottumuttu <sai.teja.pottumuttu@intel.com>
=> Iris: Fix to release BO immediately if not busy

src/egl/drivers/dri2/platform_android.c, src/egl/drivers/dri2/platform_android.h, src/egl/drivers/dri2/platform_android_mapper.cpp
Previously buffer info getting for YUV format by gralloc4 is not complete for egl image creation. Need calculate extra chroma information from layout info.
Tracked-On: OAM-106557
=> Make gralloc4 mapper support YUV format

src/gallium/drivers/iris/iris_bufmgr.c
Revert "INTERNAL: Iris: Fix to release BO immediately if not busy"
This reverts commit https://github.com/projectceladon/external-mesa/commit/3d6c7fb87ae85068311083d52832ddc0b4e7b59e.
Tracked-On: OAM-108904
Signed-off-by: Jia, Lin A <lin.a.jia@intel.com>
=> Revert "INTERNAL: Iris: Fix to release BO immediately if not busy"

src/intel/vulkan/anv_android.c, src/intel/vulkan/anv_image.c, src/intel/vulkan/anv_private.h
It is observed that in display resolutions where width is not equal to stride, vulkan rendering is being distorted. This is happening due to a stride calculation mismatch between minigbm and mesa.
This fix makes sure that the stride calculated in minigbm is passed to anv and isl.
The fix resolves the following two android CTS issues android.graphics.cts.VulkanPreTransformTest#testVulkanPreTransformNotSetToMatchCurrentTransform android.graphics.cts.VulkanPreTransformTest#testVulkanPreTransformSetToMatchCurrentTransform
Tracked-On: OAM-106986
Signed-off-by: Sai Teja Pottumuttu <sai.teja.pottumuttu@intel.com>
=> anv: Fix stride mismatch in mesa and minigbm

src/gallium/drivers/iris/iris_batch.c, src/intel/common/meson.build
Frame no is specified by env CAPTURE_FRAME_NO
On IVI,the buffer file path is /data/local/tmp/mesa3d_intel.
On Linux, the buffer file path is /tmp/mesa3d_intel
Usage:
INTEL_DEBUG=bat CAPTURE_FRAME_NO=3692 aicreplay xxx.trace
=> Dump specified frame batch buffer

src/gallium/drivers/iris/iris_resource.c
This is a workaround solution to fix rendering corruption for CCS format texture when copying the compressed data.
TODO: Improve this solution
when identifying the true root cause of this issue.
Tracked-On: OAM-113382
Signed-off-by: Li,Gaoshun <gaoshun.li@intel.com>
=> Fix a rendering corruption for CCS format texture

src/intel/vulkan/anv_device.c
VK_EXT_swapchain_maintenance1 is supported since Android 14 so enable it in vulkan driver to pass CTS test.
Tracked-On: OAM-117264
=> anv: Enable VK_EXT_swapchain_maintenance1 on Android 14

src/vulkan/wsi/wsi_common.c
KHR_present_wait is not supported well on android platform, it's already disabled in driver, but it's conditional. The logic to detect whether to enable this extension is not robust and causes this extension to be enabled in CTS test:
dEQP-VK.wsi.android.present_id_wait.*. So force disable it to fix this issue.
Tracked-On: OAM-118018
=> anv: Force disable KHR_present_wait on android platform

src/intel/common/i915/intel_gem.c
GPU timestamp register can't be accessed from VF with DRM_IOCTL_I915_REG_READ so disable it.
Tracked-On: OAM-118226
=> anv: Disable VK_EXT_calibrated_timestamps

src/intel/vulkan/anv_android.c
Tiled scan-out buffer works only for those platforms supporting set_tiling/get_tiling ioctl, which is not used for newer platforms (e.g., dGPU).  This change switch to querying modifier reliably with gralloc API.
Tracked-On: OAM-117994
Reviewed-by: Tapani Pälli <tapani.palli@intel.com>
Reviewed-by: Lionel Landwerlin <lionel.g.landwerlin@intel.com>
Part-of: <https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/29185>
=> anv/anroid: Query gralloc for tiling mode

src/egl/drivers/dri2/platform_android.c
Add format r10g10b10a2 to egl config, do not require recordable to be 1
=> egl/android: Fix unsupported egl config r10g10b10a2, recordable_android=0 for media cts

src/util/u_gralloc/u_gralloc_imapper4_api.cpp
Previously the dataspace data for YUV is hardcoded. Since gralloc4 can retrieve the dataspace data now, we just set a default value and try to get real value from gralloc4.
Tracked-On: OAM-119899
=> Fix cts DecodeGlAccuracyTest fail

src/intel/vulkan/grl/meson.build
Fix race condition when building ANV:
In file included from src/intel/vulkan/grl/grl_metakernel_build_primref.c:40:
../src/intel/common/mi_builder.h:28:10: fatal error: 'genxml/genX_bits.h' file not found
#include "genxml/genX_bits.h"
This change is already included in commit
41b2ed65e2532fd3be9ee7b74c74401169e81acd (genxml: generate opencl packing headers) in the upstream.  Hence when updating mesa version, this change can be safely removed.
=> anv: Add idep_genxml to dependencies of grl_genX_libs

src/gallium/frontends/dri/dri2.c, src/gallium/frontends/dri/drisw.c, src/gallium/frontends/dri/kopper.c
Without this patch when dri driver fails to load, the process will crash due to double releasing.
Detail: `dri_release_screen()` will be called twice when `dri2_init_screen()` fails in `driCretateNewScreen2()`.
=> Backport upstream fix

src/egl/drivers/dri2/platform_android.c, src/intel/common/intel_check.c, src/intel/common/intel_check.h, src/intel/vulkan/anv_device.c
Check the dGPU through whether has local memory.
Calculate the i915 render node number for better
compatibility.
The GLES open one available render node, vulkan
open all available render nodes.
Enalbe the vulkan dGPU render.
Tracked-On: OAM-122333
=> Refine the dGPU render

src/intel/vulkan/genX_init_state.c
Ported from upstream:
https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/30841?commit_id=1f9c40a8d1b2ec3702862371af3a934e9a0c9cda
The default state doesn't seem well defined (or kernel driver bug maybe?). Let's just set it to disabled on platforms where we're not using it.
Signed-off-by: Lionel Landwerlin <lionel.g.landwerlin@intel.com>
Cc: mesa-stable
Found-by: Chuansheng Liu <chuansheng.liu@intel.com>
Reviewed-by: Tapani Pälli <tapani.palli@intel.com>
Part-of: <https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/30841>
Tracked-On: OAM-124615
=> anv: explicitly disable BT pool allocations at device init

android/Android.mk, meson.build, src/util/u_gralloc/meson.build, src/util/u_gralloc/u_gralloc.c, src/util/u_gralloc/u_gralloc_imapper5_api.cpp, src/util/u_gralloc/u_gralloc_internal.h
As IMapper4 is deprecated from Android15, changes done to use IMapper5 stable-c mapper.
Tests done:
- Android boot in GVT-d and BM config
- adb reboot
Tracked-On: OAM-124485
=> Changes to use IMapper5 stable-c mapper

meson_options.txt
Tests done:
- Android boot in GVT-d mode with xe driver enabled
Tracked-On: OAM-124802
=> Enable Xe kernel mode driver support

meson.build, src/gallium/auxiliary/pipe-loader/meson.build, src/gallium/auxiliary/pipe-loader/pipe_loader_drm.c, src/gallium/auxiliary/target-helpers/drm_helper.h, src/gallium/drivers/iris/iris_resource.c, src/gallium/drivers/iris/iris_resource.h, src/gallium/drivers/iris/iris_screen.c, src/gallium/drivers/iris/iris_screen.h, src/gallium/winsys/iris/drm/iris_drm_public.h, src/gallium/winsys/iris/drm/iris_drm_winsys.c, src/gallium/winsys/iris/drm/meson.build, src/gallium/winsys/kmsro/drm/kmsro_drm_winsys.c, src/loader/loader.c
Now that ACRN SOS uses celadon Mesa, port patches for SOS Mesa to this repo. This will reduce maintenance effort.
=> Alignment of Mesa in AAOS and SOS

android/Android.mk, android/mesa3d_cross.mk, android/perfetto/pps-producer.cc, src/intel/ds/intel_driver_ds.cc, src/intel/ds/intel_pps_driver.cc, src/tool/pps/cfg/gpu.cfg, src/tool/pps/cfg/intel.cfg, src/tool/pps/cfg/system.cfg, src/tool/pps/pps_datasource.cc, src/tool/pps/pps_producer.cc
Rename the perfetto gpu data producer name from libpps-producer
to libgpudataproducer to align with AGI/cts.
To pass the test, it also need following cmd:
1, echo "0" > /proc/sys/dev/i915/perf_stream_paranoid 2, setenforce 0
3, sysctl dev.i915.perf_stream_paranoid=0
sysctl dev.i915_ag.perf_stream_paranoid=0
When in vm mode, at least 1 gpu needs to be passthoughed. SRIOV mode has no metrics info provided under dir:
/sys/dev/char/%d:%d/device/drm
Tracked-On: OAM-128278
=> Fix CtsGpuProfilingDataTest fail

src/intel/blorp/blorp_clear.c
For RGB565D0S0MS0,some pixels will be cleared incorrectly, when using the REP16 instruction on the DG2 platform to accelerate slow clear. 
Ref link: https://hsdes.intel.com/appstore/article-one/article/14017880152. 
For example, with glClear(0.125, 0.25, 0.5, 1), the corresponding pixel values are (32, 64, 128). 
When using the REP16 instruction on the DG2 platform to accelerate slow clear, some pixels will be cleared to (24, 60, 120).
Tracked-On: OAM-123699
Signed-off-by: Li,Gaoshun gaoshun.li@intel.com
=> Fixed a DEQP bug on DG2

src/intel/common/intel_check.c
Check whether have the prop set.
Tracked-On: OAM-127209
=> Check the app and process name

src/intel/common/intel_check.c
Some app has error while setting the dGPU relate property using the process name, like the .benchmark.auto.
Change to use app name instead.
persist.vendor.intel.dGPUwSys+app_name
persist.vendor.intel.dGPUwLocal+app_name
Tracked-On: OAM-129468
=> Change to check the app name

src/intel/isl/isl_format.c
The dEQP-VK.image.extended_usage_bit_compatibility.image_format_list test cases failed. 
This is because the corresponding format is not a Supported Typed Surface Write Format on ADL/RPl.
According to the specification, update the support status of the format on ADL/RPl. 
Tracked-On: OAM-130817
=> Fixed 8 deqp cts failures.

src/util/u_gralloc/u_gralloc_imapper5_api.cpp
In case of legacy dataspace value is passed down by framework/av/media code.
Tracked-On: OAM-130969
=> Add legacy dataspace value supporting

src/intel/common/intel_check.c
The file is placed at /vendor/etc/config.txt where do not need extra policy to read the file.
Add the 15 length process name to the config.txt if would like to use dgpu render.
Tracked-On: OAM-131149
=> Check the config file to detect dgpu render process

src/intel/isl/isl_format.c
This reverts commit fed29ac3f907e960999e39272711e5858d373ad1.
When the corresponding cases are tested using the updated test package(android15-r3), they no longer fail.
Therefore, we should revert this patch.
Tracked-On: OAM-131224
=> Revert "Fixed 8 deqp cts failures."

src/intel/common/intel_check.c
The dgpu render and system memory doesn't reduce the usage of local memory. Delete it.
Tracked-On: OAM-131507
=> Delete the dGPU render and system memory setting
